#---------------------------------#
#      general configuration      #
#---------------------------------#

environment:
  nuget_api_key:
    secure: McEEP7IEB2tb6Eq4C5LuXTWtJ6Aao6VGJK3FrfdhcmVxbeupFzKehhaZ+JFqbcpp

# version format
version: 0.2.{build}

# Build worker image (VM template)
image: Visual Studio 2017

# clone directory
clone_folder: c:\projects\VL.OpenCV

branches:
  only:
    - master

# enable patching of AssemblyInfo.* files
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}-alpha'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}-alpha'


install:
  appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

before_build:
  - msbuild src\VL.OpenCV.csproj /v:m /t:Restore /p:Configuration=Release

build:
  project: src\VL.OpenCV.sln      # path to Visual Studio solution or project
  publish_nuget: false             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: false     # generate and publish NuGet symbol packages
  include_nuget_references: true  # add -IncludeReferencedProjects option while packaging NuGet artifacts

after_build:
  - nuget setApiKey %nuget_api_key%
  - nuget push src\bin\Release\VL.OpenCV.%APPVEYOR_BUILD_VERSION%-alpha.nupkg -Source https://api.nuget.org/v3/index.json
    
artifacts:
  - path: 'src\bin\Release\*.nupkg'
    type: NuGetPackage
  
#---------------------------------#
#         notifications           #
#---------------------------------#

test: off

notifications:

  # Email
  - provider: Email
    to:
      - ravazquez@gmail.com
    subject: 'VL.OpenCV Build {{status}}'                  # optional
    message: "{{message}}, {{commitId}}, ..."    # optional
    on_build_status_changed: true